const crypto=require('crypto');

const STATES=new Set(['Alabama','Alaska','Arizona','Arkansas','California','Colorado','Connecticut','Delaware','District of Columbia','Florida','Georgia','Hawaii','Idaho','Illinois','Indiana','Iowa','Kansas','Kentucky','Louisiana','Maine','Maryland','Massachusetts','Michigan','Minnesota','Mississippi','Missouri','Montana','Nebraska','Nevada','New Hampshire','New Jersey','New Mexico','New York','North Carolina','North Dakota','Ohio','Oklahoma','Oregon','Pennsylvania','Rhode Island','South Carolina','South Dakota','Tennessee','Texas','Utah','Vermont','Virginia','Washington','West Virginia','Wisconsin','Wyoming']);
const SESSION_COOKIE='daily_letter_session',ADMIN_COOKIE='daily_letter_admin';
const json=(status,body,headers={})=>({statusCode:status,headers:{'Content-Type':'application/json','Cache-Control':'no-store',...headers},body:JSON.stringify(body)});
const clean=(v,max=100)=>String(v||'').trim().slice(0,max);
const hash=v=>crypto.createHash('sha256').update(v).digest('hex');
const cookieMap=value=>Object.fromEntries(String(value||'').split(';').map(x=>x.trim().split(/=(.*)/s).slice(0,2)).filter(x=>x[0]).map(([k,v])=>[k,decodeURIComponent(v||'')]));
const cookie=(name,value,maxAge)=>`${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`;
function safeEqual(a,b){const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function config(){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('Server configuration is incomplete');return{url:url.replace(/\/$/,''),key}}
async function db(table,query='',options={}){const {url,key}=config();const response=await fetch(`${url}/rest/v1/${table}${query?'?'+query:''}`,{method:options.method||'GET',headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:options.prefer||'return=representation'},body:options.body?JSON.stringify(options.body):undefined});const text=await response.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!response.ok){console.error('Database request failed',response.status,data);const err=new Error('Database request failed');err.status=response.status;err.details=data;throw err}return data}
function makePassword(password,salt=crypto.randomBytes(16).toString('hex')){return new Promise((resolve,reject)=>crypto.scrypt(password,salt,64,(e,key)=>e?reject(e):resolve({salt,passwordHash:key.toString('hex')})))}
async function verifyPassword(password,salt,expected){const made=await makePassword(password,salt);return safeEqual(made.passwordHash,expected)}
function publicProfile(p){return{id:p.id,username:p.username,firstName:p.first_name,lastName:p.last_name,age:p.age,phone:p.phone,street:p.street_address,city:p.city,state:p.state,zip:p.zip_code}}
async function playerStats(playerId){const rows=await db('game_results',`select=puzzle_number,won,guesses,created_at&player_id=eq.${playerId}&order=puzzle_number.asc`);const games=new Map();for(const row of rows||[]){const prior=games.get(row.puzzle_number);if(!prior||row.won||(!prior.won&&row.guesses<prior.guesses))games.set(row.puzzle_number,row)}const ordered=[...games.values()].sort((x,y)=>x.puzzle_number-y.puzzle_number);let best=0,run=0;for(const game of ordered){run=game.won?run+1:0;best=Math.max(best,run)}let streak=0;for(let i=ordered.length-1;i>=0&&ordered[i].won;i--){if(i<ordered.length-1&&ordered[i+1].puzzle_number!==ordered[i].puzzle_number+1)break;streak++}return{played:ordered.length,wins:ordered.filter(x=>x.won).length,streak,best}}
async function createSession(playerId){const token=crypto.randomBytes(32).toString('base64url'),expires=new Date(Date.now()+365*86400000).toISOString();await db('player_sessions','',{method:'POST',body:{player_id:playerId,token_hash:hash(token),expires_at:expires,last_seen_at:new Date().toISOString()}});return token}
async function playerFromEvent(event,touch=false){const token=cookieMap(event.headers.cookie)[SESSION_COOKIE];if(!token)return null;const sessions=await db('player_sessions',`select=player_id,expires_at&token_hash=eq.${hash(token)}&expires_at=gt.${encodeURIComponent(new Date().toISOString())}&limit=1`);if(!sessions?.length)return null;if(touch)db('player_sessions',`token_hash=eq.${hash(token)}`,{method:'PATCH',body:{last_seen_at:new Date().toISOString()},prefer:'return=minimal'}).catch(()=>{});const profiles=await db('player_profiles',`select=id,username,first_name,last_name,age,phone,street_address,city,state,zip_code,account_status&id=eq.${sessions[0].player_id}&limit=1`);return profiles?.[0]&&profiles[0].account_status!=='disabled'?profiles[0]:null}
function adminToken(){const exp=Date.now()+8*3600000,payload=String(exp),sig=crypto.createHmac('sha256',process.env.SESSION_SECRET||'').update('admin:'+payload).digest('hex');return payload+'.'+sig}
function isAdmin(event){const token=cookieMap(event.headers.cookie)[ADMIN_COOKIE];if(!token)return false;const [exp,sig]=token.split('.');if(!exp||!sig||Number(exp)<Date.now())return false;const expected=crypto.createHmac('sha256',process.env.SESSION_SECRET||'').update('admin:'+exp).digest('hex');return safeEqual(sig,expected)}
function validateProfile(b){const data={firstName:clean(b.firstName,30),lastName:clean(b.lastName,30),age:Number(b.age),phone:clean(b.phone,20).replace(/^\+?1\s*/,''),street:clean(b.street,100),city:clean(b.city,50),state:clean(b.state,30),zip:clean(b.zip,10),username:clean(b.username,24).toLowerCase(),password:String(b.password||'')};if(!data.firstName||!data.lastName||!data.street||!data.city||!b.consent)throw new Error('Please complete every field and accept the consent statement.');if(!Number.isInteger(data.age)||data.age<18||data.age>120)throw new Error('Enter a valid age.');if(!/^[a-z0-9_]{4,24}$/.test(data.username))throw new Error('Username must contain 4–24 letters, numbers, or underscores.');if(!/^[0-9() .-]{10,16}$/.test(data.phone))throw new Error('Enter a valid U.S. phone number.');if(!STATES.has(data.state))throw new Error('Select a valid U.S. state.');if(!/^\d{5}(-\d{4})?$/.test(data.zip))throw new Error('Enter a valid ZIP code.');if(data.password.length<8||data.password.length>128)throw new Error('Password must contain 8–128 characters.');return data}

function validateProfileUpdate(b){const data={firstName:clean(b.firstName,30),lastName:clean(b.lastName,30),age:Number(b.age),phone:clean(b.phone,20).replace(/^\+?1\s*/,''),street:clean(b.street,100),city:clean(b.city,50),state:clean(b.state,30),zip:clean(b.zip,10)};if(!data.firstName||!data.lastName||!data.street||!data.city)throw new Error('Please complete every field.');if(!Number.isInteger(data.age)||data.age<18||data.age>120)throw new Error('Please enter a valid age.');if(!/^[0-9() .-]{10,16}$/.test(data.phone))throw new Error('Please enter a valid U.S. phone number.');if(!STATES.has(data.state))throw new Error('Please select a valid U.S. state.');if(!/^\d{5}(-\d{4})?$/.test(data.zip))throw new Error('Please enter a valid ZIP code.');return data}

exports.handler=async(event)=>{
  if(!process.env.SESSION_SECRET||!process.env.ADMIN_PASSWORD)return json(503,{error:'Server configuration is incomplete.'});
  const action=new URLSearchParams(event.rawQuery||event.queryStringParameters&&new URLSearchParams(event.queryStringParameters).toString()||'').get('action')||'me';
  let body={};if(event.body){try{body=JSON.parse(event.body)}catch{return json(400,{error:'Invalid request.'})}}
  try{
    if(action==='register'&&event.httpMethod==='POST'){const d=validateProfile(body);const existing=await db('player_profiles',`select=id&username=eq.${encodeURIComponent(d.username)}&limit=1`);if(existing?.length)return json(409,{error:'That username is already taken. Please choose another.'});const pass=await makePassword(d.password);let rows;try{rows=await db('player_profiles','',{method:'POST',body:{username:d.username,first_name:d.firstName,last_name:d.lastName,age:d.age,phone:'+1 '+d.phone,street_address:d.street,city:d.city,state:d.state,zip_code:d.zip,password_hash:pass.passwordHash,password_salt:pass.salt,account_status:'active'}})}catch(e){if(e.status===409)return json(409,{error:'That username is already taken. Please choose another.'});throw e}const token=await createSession(rows[0].id);return json(201,{profile:publicProfile(rows[0]),stats:{played:0,wins:0,streak:0,best:0}},{'Set-Cookie':cookie(SESSION_COOKIE,token,31536000)})}
    if(action==='login'&&event.httpMethod==='POST'){const username=clean(body.username,24).toLowerCase(),password=String(body.password||'');const rows=await db('player_profiles',`select=id,username,first_name,last_name,age,phone,street_address,city,state,zip_code,password_hash,password_salt,account_status&username=eq.${encodeURIComponent(username)}&limit=1`);const p=rows?.[0];if(!p||p.account_status==='disabled'||!await verifyPassword(password,p.password_salt,p.password_hash))return json(401,{error:'Username or password is incorrect.'});const token=await createSession(p.id),stats=await playerStats(p.id);return json(200,{profile:publicProfile(p),stats},{'Set-Cookie':cookie(SESSION_COOKIE,token,31536000)})}
    if(action==='logout'&&event.httpMethod==='POST'){const token=cookieMap(event.headers.cookie)[SESSION_COOKIE];if(token)await db('player_sessions',`token_hash=eq.${hash(token)}`,{method:'DELETE',prefer:'return=minimal'}).catch(()=>{});return json(200,{ok:true},{'Set-Cookie':cookie(SESSION_COOKIE,'',0)})}
    if(action==='update-profile'&&event.httpMethod==='POST'){const p=await playerFromEvent(event,true);if(!p)return json(401,{error:'Please log in again.'});const d=validateProfileUpdate(body);const rows=await db('player_profiles',`id=eq.${p.id}`,{method:'PATCH',body:{first_name:d.firstName,last_name:d.lastName,age:d.age,phone:'+1 '+d.phone,street_address:d.street,city:d.city,state:d.state,zip_code:d.zip}});return json(200,{profile:publicProfile(rows[0])})}
    if(action==='me'){const p=await playerFromEvent(event,true);return json(200,{profile:p?publicProfile(p):null,stats:p?await playerStats(p.id):null})}
    if(action==='heartbeat'&&event.httpMethod==='POST'){const p=await playerFromEvent(event,true);return p?json(200,{ok:true}):json(401,{error:'Please log in again.'})}
    if(action==='result'&&event.httpMethod==='POST'){const p=await playerFromEvent(event,true);if(!p)return json(401,{error:'Please log in first.'});const puzzleNumber=Number(body.puzzleNumber),guesses=Number(body.guesses),won=!!body.won;if(!Number.isInteger(puzzleNumber)||!Number.isInteger(guesses)||guesses<1||guesses>6)return json(400,{error:'Invalid game result.'});await db('game_results','',{method:'POST',body:{player_id:p.id,puzzle_number:puzzleNumber,guesses,won}});return json(201,{ok:true,stats:await playerStats(p.id)})}
    if(action==='admin-login'&&event.httpMethod==='POST'){if(!safeEqual(String(body.password||''),process.env.ADMIN_PASSWORD))return json(401,{error:'Incorrect administrator password.'});return json(200,{ok:true},{'Set-Cookie':cookie(ADMIN_COOKIE,adminToken(),28800)})}
    if(action==='admin-logout'&&event.httpMethod==='POST')return json(200,{ok:true},{'Set-Cookie':cookie(ADMIN_COOKIE,'',0)});
    if(action==='admin-data'){if(!isAdmin(event))return json(401,{error:'Administrator login required.'});const [players,sessions,results]=await Promise.all([db('player_profiles','select=id,username,first_name,last_name,age,phone,street_address,city,state,zip_code,created_at,account_status&order=created_at.desc'),db('player_sessions','select=player_id,last_seen_at,expires_at&order=last_seen_at.desc'),db('game_results','select=player_id,won,guesses,created_at')]);const now=Date.now(),activeToday=new Set(sessions.filter(s=>now-new Date(s.last_seen_at).getTime()<86400000).map(s=>s.player_id)),online=new Set(sessions.filter(s=>now-new Date(s.last_seen_at).getTime()<300000).map(s=>s.player_id));const games=new Map();for(const r of results){const x=games.get(r.player_id)||{played:0,wins:0};x.played++;if(r.won)x.wins++;games.set(r.player_id,x)}return json(200,{summary:{registered:players.length,activeToday:activeToday.size,online:online.size,games:results.length},players:players.map(p=>({...p,online:online.has(p.id),last_seen:sessions.find(s=>s.player_id===p.id)?.last_seen_at||null,games:games.get(p.id)||{played:0,wins:0}}))})}
    return json(404,{error:'Not found.'});
  }catch(error){console.error(error);return json(error.status===400?400:500,{error:error.message&&error.message.startsWith('Please')?error.message:'The server could not complete this request. Please try again.'})}
};
